ProjectType.Web/Models/ErrorViewModel.cs
namespace ProjectType.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ProjectType.Web/Controllers/Apis/ProjectTypesController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectType.Application.Dtos;
using ProjectType.Application.Services.ProjectType;

namespace ProjectType.Web.Controllers.Apis;

[ApiController]
[Route("api/[controller]")]
public class ProjectTypesController : ControllerBase
{
    private readonly IProjectTypeService _projectTypeService;

    public ProjectTypesController(IProjectTypeService projectTypeService)
    {
        _projectTypeService = projectTypeService;
    }
    
    [HttpGet]
    public async Task<IActionResult> GetProjectTypes()
    {
        var projectTypes = await _projectTypeService.GetProjectTypes();
        
        return Ok(projectTypes);
    }
    
    [HttpPost]
    public async Task<IActionResult> AddProjectType(ProjectTypeDto projectType)
    {
        await _projectTypeService.AddProjectType(projectType);
        
        return Ok("Project Type added successfully");
    }
    
    [HttpPut("{id}")]
    public async Task<IActionResult> UpdateProjectType(int id, ProjectTypeDto projectType)
    {
        try
        {
            await _projectTypeService.UpdateProjectType(id, projectType);
        
            return Ok("Project Type updated successfully");
        }
        catch (Exception e)
        {
            return BadRequest(e.Message);
        }
    }
    
    [HttpDelete("{id}")]
    public async Task<IActionResult> DeleteProjectType(int id)
    {
        try
        {
            await _projectTypeService.DeleteProjectType(id);
        
            return Ok("Project Type deleted successfully");
        }
        catch (Exception e)
        {
            return BadRequest(e.Message);
        }
    }
}

ProjectType.Web/Controllers/ProjectTypeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ProjectType.Application.Dtos;
using ProjectType.Application.Services.ProjectType;
using ProjectType.Application.ViewModels;

namespace ProjectType.Web.Controllers;

public class ProjectTypeController : Controller
{
    private readonly IProjectTypeService _projectTypeService;
    private readonly IMapper _mapper;

   
    public ProjectTypeController(IProjectTypeService projectTypeService, IMapper mapper)
    {
        _projectTypeService = projectTypeService;
        _mapper = mapper;
    }
    
    public async Task<IActionResult> Index()
    {
        var projectTypes = await _projectTypeService.GetProjectTypes();
        
        var projectTypesModels = _mapper.Map<IEnumerable<ProjectTypeViewModel>>(projectTypes);
        
        return View(projectTypesModels);
    }
    
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(ProjectTypeViewModel projectType)
    {
        if (!ModelState.IsValid) 
            return View(projectType);
        
        var projectTypeDto = _mapper.Map<ProjectTypeDto>(projectType);
            
        await _projectTypeService.AddProjectType(projectTypeDto);
            
        return RedirectToAction("Index");
    }
    
    [HttpGet]
    public async Task<IActionResult> Update(int id)
    {
        var projectType = await _projectTypeService.GetProjectType(id);
        
        var projectTypeModel = _mapper.Map<ProjectTypeViewModel>(projectType);
            
        return View(projectTypeModel);
    }

    [HttpPost]
    public async Task<IActionResult> Update(ProjectTypeViewModel projectType)
    {
        if (!ModelState.IsValid) 
            return View(projectType);
        
        var projectTypeDto = _mapper.Map<ProjectTypeDto>(projectType);
            
        await _projectTypeService.UpdateProjectType(projectTypeDto.Id, projectTypeDto);
            
        return RedirectToAction("Index");
    }
    
    public async Task<IActionResult> Delete(int id)
    {
        await _projectTypeService.DeleteProjectType(id);
        
        return RedirectToAction("Index");
    }
}

ProjectType.Web/Views/ProjectType/Create.cshtml
@model ProjectTypeViewModel

@{
    ViewBag.Title = "Create Project Type";
    Layout = "_Layout";
}

<div class="container mt-5">
    <h2>@ViewData["Title"]</h2>
    <form asp-action="Create" method="post">
        <div class="mb-3">
            <label asp-for="@Model.Name" class="form-label"></label>
            <input type="text" asp-for="@Model.Name" class="form-control"/>
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Create</button>
            <a asp-action="Index" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ProjectType.Web/Views/ProjectType/Index.cshtml
@model IEnumerable<ProjectTypeViewModel>

@{
    ViewBag.Title = "Project Type";
    Layout = "_Layout";
}

<div class="container mt-5">
    <div class="mb-3">
        <a asp-action="Create" class="btn btn-success">Create Project Type</a>
    </div>
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>
                    <a href="ProjectType/Update/@item.Id" class="btn btn-primary btn-sm"> Update </a>
                    <a onclick="DeleteProjectType(@item.Id)" class="btn btn-danger btn-sm"> Delete </a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

@section Scripts {
    <script>
        function DeleteProjectType(id) {
            $.ajax({
                url: '/ProjectType/Delete/' + id,
                type: 'DELETE',
                success: function(result) {
                   window.location.href = '/ProjectType/Index';
                },
                error: function(xhr, status, error) {
                    console.error('Error deleting project type:', error);
                    alert('Failed to delete the project type.');
                }
            });
        }
    </script>
}

ProjectType.Web/Views/ProjectType/Update.cshtml
@model ProjectTypeViewModel

@{
    ViewBag.Title = "Update Project Type";
    Layout = "_Layout";
}

<div class="container mt-5">
    <h2>@ViewData["Title"]</h2>
    <form asp-action="Update" method="post">
        <input type="hidden" name="id" value="@Model.Id"/>
        <div class="mb-3">
            <label asp-for="@Model.Name" class="form-label"></label>
            <input type="text" asp-for="@Model.Name" class="form-control"/>
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Update</button>
            <a asp-action="Index" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ProjectType.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - ProjectType </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>

</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="ProjectType" asp-action="Index">ProjectType</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ProjectType" asp-action="Index">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - ProjectType - Privacy
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>